version: '3.8'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/jenkins-home:/var/jenkins_home"
    networks:
      - net

networks:
  net: